Updates required to run SNAPRed
SNAPRed seems to require a later build of mantidworkbench to run, otherwise I get an exception:

  File ".../SNAPRed/src/snapred/backend/recipe/algorithm/RemoveEventBackground.py", line 14, in <module>
    from mantid.simpleapi import (
ImportError: cannot import name 'GroupedDetectorIDs' from 'mantid.simpleapi' (.../anaconda3/envs/SNAPRed/lib/python3.10/site-packages/mantid/simpleapi.py)